---
dependency:
  name: galaxy
driver:
  name: docker

role_name_check: 1
platforms:
  - name: telegraf-${MY_MOLECULE_CONTAINER:-centos8}
    image: ${MY_MOLECULE_IMAGE:-"geerlingguy/docker-centos8-ansible"}
    command: ${MY_MOLECULE_DOCKER_COMMAND:-""}
    privileged: True
    pre_build_image: True
    cgroupns_mode: host
    networks:
      - name: telegraf
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - telegraf

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      debian:
        telegraf_agent_package_method: online
      all:
        telegraf_agent_package_state: latest
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = ["http://influxdb:8086"]
              - database = "telegraf"
              - precision = "s"
        telegraf_plugins_extra:
          logparser:
            plugin: logparser
            config:
              - files = ["/var/log/messages"]
              - from_beginning = false
            filter:
              name: grok
              config:
                - patterns = ["invoked oom-killer"]
        telegraf_aggregators:
          - aggregator: basicstats
            config:
              - drop_original = false
              - stats = ['mean']
            tagpass:
              - cpu = ["cpu-total"]

scenario:
  name: empty-checkmode
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
