---

- hosts: telegraf
  tasks:
    - name: "Installing packages on CentOS"
      yum:
        name: which
        state: present
      when:
        - ansible_os_family == 'RedHat'

    - name: "Apt get update"
      shell: apt-get update && apt-get install -y python-apt
      when:
        - ansible_os_family == 'Debian'

    - name: debug
      debug:
        var: ansible_distribution_major_version

    - name: "Installing packages on Debian"
      apt:
        name:
          - wget
          - python-apt
          - "{{ 'gnupg-agent' if ansible_distribution_major_version in ['8', '18', '16'] else 'gpg-agent' }}"
        update_cache: True
        state: present
      when:
        - ansible_os_family == 'Debian'

    - name: "Installing packages on Suse"
      zypper:
        name:
          - sysvinit-tools
          - insserv-compat
          - aaa_base
        state: present
      when:
        - ansible_os_family == 'Suse'
